name: tuple
version: 0.2.0
authors:
- Boris Kaul <localvoid@gmail.com>
- Kwang Yul Seo <kwangyul.seo@gmail.com>
description: Tuple data structure
homepage: https://github.com/kseo/tuple
environment:
  sdk: '>=1.6.0'
dev_dependencies:
  test: any
